// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/htslibr.h"
#include <Rcpp.h>

using namespace Rcpp;

// read_bam
DataFrame read_bam(std::string bampath);
RcppExport SEXP _htslibr_read_bam(SEXP bampathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bampath(bampathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bam(bampath));
    return rcpp_result_gen;
END_RCPP
}
